/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMessageBody {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "interaction_id")]
    pub interaction_id: String,
    #[serde(rename = "message_order")]
    pub message_order: i32,
    #[serde(rename = "interaction_order")]
    pub interaction_order: i32,
    #[serde(rename = "flow_id")]
    pub flow_id: String,
    #[serde(rename = "step_id")]
    pub step_id: String,
    #[serde(rename = "direction")]
    pub direction: Direction,
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

impl CreateMessageBody {
    pub fn new(id: String, interaction_id: String, message_order: i32, interaction_order: i32, flow_id: String, step_id: String, direction: Direction, payload: serde_json::Value) -> CreateMessageBody {
        CreateMessageBody {
            id,
            interaction_id,
            message_order,
            interaction_order,
            flow_id,
            step_id,
            direction,
            payload,
            text: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "SEND")]
    SEND,
    #[serde(rename = "RECEIVE")]
    RECEIVE,
}

