/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateConversationBody {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "flow_id", skip_serializing_if = "Option::is_none")]
    pub flow_id: Option<String>,
    #[serde(rename = "step_id", skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl CreateConversationBody {
    pub fn new(id: String, metadata: serde_json::Value, flow_id: Option<String>, step_id: Option<String>) -> CreateConversationBody {
        CreateConversationBody {
            id,
            flow_id,
            step_id,
            metadata,
        }
    }
}


