/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject2 {
    #[serde(rename = "success")]
    pub success: bool,
}

impl InlineObject2 {
    pub fn new(success: bool) -> InlineObject2 {
        InlineObject2 {
            success,
        }
    }
}


