/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2001 {
    #[serde(rename = "processed")]
    pub processed: bool,
}

impl InlineResponse2001 {
    pub fn new(processed: bool) -> InlineResponse2001 {
        InlineResponse2001 {
            processed,
        }
    }
}


