/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "client")]
    pub client: crate::models::ClientModel,
    #[serde(rename = "type")]
    pub _type: String,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: serde_json::Value,
    #[serde(rename = "private", skip_serializing_if = "Option::is_none")]
    pub private: Option<bool>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl StateModel {
    pub fn new(id: String, client: crate::models::ClientModel, _type: String, key: String, value: serde_json::Value) -> StateModel {
        StateModel {
            id,
            client,
            _type,
            key,
            value,
            private: None,
            expires_at: None,
        }
    }
}
