[package]
name = "csmlinterpreter"
version = "0.1.0"
authors = ["amerelo <alexis.merelo@clevy.io>"]
edition = "2018"

[lib]
name = "csmlinterpreter"
crate-type = ["rlib"]

[features] 
default = ["rustls-tls"]
rustls-tls = []

[dependencies]
nom_locate = "0.3.1"
nom =  "4.2.3"
rand = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
multimap = "0.6.0"
reqwest = { version = "0.9.19", features = ["rustls-tls"]}

[[example]]
name = "test_flow"