[package]
name = "csmlinterpreter"
version = "0.1.0"
authors = ["amerelo <alexis.merelo@clevy.io>"]
edition = "2018"

[lib]
name = "csmlinterpreter"
crate-type = ["rlib"]

[dependencies]
nom_locate = "0.3.1"
nom = "4.2.3"
rand = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
multimap = "0.5.0"
reqwest = "0.9.17"

[[example]]
name = "test_flow"