[workspace]
members = [
    "csml_interpreter",
    "csml_engine",
    "csml_server",
    "csml_cli",
    "bindings/node/native",
    "bindings/aws_lambda",

    "bindings/ios",
    "bindings/android"
]

[profile.test]
opt-level = 1
