[package]
name = "nom_csml_v01"
version = "0.1.0"
authors = ["amerelo <alexis.merelo@clevy.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
nom = "4.2.2"
rand = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2.50"