/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use reqwest;

use super::{Error, configuration};

pub struct NodesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl NodesApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> NodesApiClient {
        NodesApiClient {
            configuration,
        }
    }
}

pub trait NodesApi {
    fn create_node(&self, conversation_id: &str, bot_id: &str, user_id: &str, channel_id: &str, create_node_body: crate::models::CreateNodeBody) -> Result<(), Error>;
    fn get_conversation_nodes(&self, conversation_id: &str, bot_id: &str, user_id: &str, channel_id: &str) -> Result<Vec<crate::models::NodeModel>, Error>;
}

impl NodesApi for NodesApiClient {
    fn create_node(&self, conversation_id: &str, bot_id: &str, user_id: &str, channel_id: &str, create_node_body: crate::models::CreateNodeBody) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/conversations/{conversationId}/nodes", configuration.base_path, conversationId=crate::apis::urlencode(conversation_id));
        let mut req_builder = client.post(uri_str.as_str());

        req_builder = req_builder.query(&[("bot_id", &bot_id.to_string())]);
        req_builder = req_builder.query(&[("user_id", &user_id.to_string())]);
        req_builder = req_builder.query(&[("channel_id", &channel_id.to_string())]);
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.json(&create_node_body);

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_conversation_nodes(&self, conversation_id: &str, bot_id: &str, user_id: &str, channel_id: &str) -> Result<Vec<crate::models::NodeModel>, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/conversations/{conversationId}/nodes", configuration.base_path, conversationId=crate::apis::urlencode(conversation_id));
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("bot_id", &bot_id.to_string())]);
        req_builder = req_builder.query(&[("user_id", &user_id.to_string())]);
        req_builder = req_builder.query(&[("channel_id", &channel_id.to_string())]);
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
