CREATE TABLE states (
  id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES client (id),

  type VARCHAR NOT NULL,
  key VARCHAR NOT NULL,
  value VARCHAR NOT NULL,

  expires_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
