CREATE TABLE interactions (
  id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES client (id),
  success BOOLEAN NOT NULL,
  event VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
