/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientModel {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "bot_id")]
    pub bot_id: String,
}

impl ClientModel {
    pub fn new(user_id: String, channel_id: String, bot_id: String) -> ClientModel {
        ClientModel {
            user_id,
            channel_id,
            bot_id,
        }
    }
}
