/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InteractionModel {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "client")]
    pub client: crate::models::ClientModel,
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "class", skip_serializing_if = "Option::is_none")]
    pub class: Option<String>,
    #[serde(rename = "event")]
    pub event: serde_json::Value,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl InteractionModel {
    pub fn new(id: String, client: crate::models::ClientModel, success: bool, event: serde_json::Value) -> InteractionModel {
        InteractionModel {
            id,
            client,
            success,
            class: None,
            event,
            created_at: None,
        }
    }
}


