/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeModel {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "conversation_id", skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(rename = "interaction_id", skip_serializing_if = "Option::is_none")]
    pub interaction_id: Option<String>,
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<crate::models::ClientModel>,
    #[serde(rename = "flow_id", skip_serializing_if = "Option::is_none")]
    pub flow_id: Option<String>,
    #[serde(rename = "next_flow", skip_serializing_if = "Option::is_none")]
    pub next_flow: Option<String>,
    #[serde(rename = "step_id", skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,
    #[serde(rename = "next_step", skip_serializing_if = "Option::is_none")]
    pub next_step: Option<String>,
    #[serde(rename = "class", skip_serializing_if = "Option::is_none")]
    pub class: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl NodeModel {
    pub fn new() -> NodeModel {
        NodeModel {
            id: None,
            conversation_id: None,
            interaction_id: None,
            client: None,
            flow_id: None,
            next_flow: None,
            step_id: None,
            next_step: None,
            class: None,
            created_at: None,
        }
    }
}


