/*
 * CSML engine microservices
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateConversationBody {
    #[serde(rename = "flow_id", skip_serializing_if = "Option::is_none")]
    pub flow_id: Option<String>,
    #[serde(rename = "step_id", skip_serializing_if = "Option::is_none")]
    pub step_id: Option<String>,
    #[serde(rename = "last_interaction", skip_serializing_if = "Option::is_none")]
    pub last_interaction: Option<bool>,
}

impl UpdateConversationBody {
    pub fn new() -> UpdateConversationBody {
        UpdateConversationBody {
            flow_id: None,
            step_id: None,
            last_interaction: None,
        }
    }
}
