name: Publish binaries

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.11
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            asset_name: csml-server-linux-amd64
          - os: macos-latest
            asset_name: csml-server-macos-amd64

    steps:
    - uses: actions/checkout@v2

    # for some reason cache does not work properly with macos builds
    - name: Cache Cargo
      if: matrix.os != 'macos-latest'
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-csml-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build Server
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --manifest-path=csml_server/Cargo.toml --features csml_engine/mongo,csml_engine/dynamo --release

    - name: Upload binary to release
      uses: svenstaro/upload-release-action@2.2.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/csml_server
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
