name: Publish CSML Engine to crates.io

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-csml-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Login
      run: cargo login ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    - name: Publish interpreter
      run: cargo publish --manifest-path csml_interpreter/Cargo.toml --all-features

    # crates.io may say that the interpreter is not available
    # if we don't wait before we build the engine
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'

    - name: Publish engine
      run: cargo publish --manifest-path csml_engine/Cargo.toml --all-features

