name: Rust

on:
  push:
    branches: [ master, dev, feat/windows_build ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.11
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install Windows dependencies
      if: matrix.os != 'windows-latest'
      run: |
        echo "::set-output name=version::$(rustc --version)"
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        vcpkg install openssl:x64-windows


    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      env:
        VCPKGRS_DYNAMIC: 1
      with:
        toolchain: stable
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      env:
        VCPKGRS_DYNAMIC: 1
      with:
        command: build
        args: --verbose --manifest-path=csml_interpreter/Cargo.toml
